= Итоги

По факту, журналирование разработки.

== 16.04.2022
Так, сегодня хочу, добавить поиск по ключу.
Идея такая, что я не хочу задумываться над _уникальностью_ генерации ключей.
По этому заменю на UUID. Хотя по факту, даже же оно может и с UUID повторятся.
Но не суть, перепроверку можно организовывать и на UUID.

Короче, основное, у меня нет знания откуда начинать последовательность.
И тут есть как минимум 2 подхода:

1. Записывать текущий счётчик в сам XML, и при создании нового "знания",
нужно будет в него заходить и читать.
2. Использовать генератор уникальных ключей.

Короче да, по поиску пока самое простое использовать Integer.
А потом переделаю на UUID.

== 01.05.2022
Добавил интернализацию.
Всегда надо эту фигню брать.
Ибо все тексты в одном месте.
И править файл ресурса как бы всегда проще, ибо в одном месте.

Так, что еще.
Сделал, обновление существующего Проверки.
А надо доделать еще и этот новая Проверка в Знании, с проверкой, есть ли уже с таким айди, и если есть, то обновить.

== 02.05.2022
Сегодня захотел продолжить эксперименты с моделью.
НО!
Остановился на том, что я свои элементы отдельно друг от друга лепил.
А ведь они же у меня друг в друга вложены!
Как это отобразить-то?!

Или по другому.

Ай была мысля и ушла.
Короче это же эксперимент!!!
А следовательно у меня тонны права на ошибку!

Так хочу порисовать или погоди.
На странице что видно, Знание -- Проверка -- список Вопросов