= Итоги

По факту, журналирование разработки.

== 16.04.2022
Так, сегодня хочу, добавить поиск по ключу.
Идея такая, что я не хочу задумываться над _уникальностью_ генерации ключей.
По этому заменю на UUID. Хотя по факту, даже же оно может и с UUID повторятся.
Но не суть, перепроверку можно организовывать и на UUID.

Короче, основное, у меня нет знания откуда начинать последовательность.
И тут есть как минимум 2 подхода:

1. Записывать текущий счётчик в сам XML, и при создании нового "знания",
нужно будет в него заходить и читать.
2. Использовать генератор уникальных ключей.

Короче да, по поиску пока самое простое использовать Integer.
А потом переделаю на UUID.

== 01.05.2022
Добавил интернализацию.
Всегда надо эту фигню брать.
Ибо все тексты в одном месте.
И править файл ресурса как бы всегда проще, ибо в одном месте.

Так, что еще.
Сделал, обновление существующего Проверки.
А надо доделать еще и этот новая Проверка в Знании, с проверкой, есть ли уже с таким айди, и если есть, то обновить.

== 02.05.2022
Сегодня захотел продолжить эксперименты с моделью.
НО!
Остановился на том, что я свои элементы отдельно друг от друга лепил.
А ведь они же у меня друг в друга вложены!
Как это отобразить-то?!

Или по другому.

Ай была мысля и ушла.
Короче это же эксперимент!!!
А следовательно у меня тонны права на ошибку!

Так хочу порисовать или погоди.
На странице, что видно, Знание -- Проверка -- список Вопросов

Да. Что-то вот делаю-делаю, "атомарно".
И как-то, хочется более, универсального.
Вот этими Дженериками если честно.

Возможно Дженериками во второй итерации.

== 07.05.2022
Так продолжаем, за сегодня надо добить вопросы и ответы.

== 30.07.2022
Однако, как я погружался в работу...

Короче, задача, на деплой на сервер.
Но для этого я хочу чтоб автоматом был файл, если его нет, то создать.
А если есть то использовать его.

И как мне _помнится_ у меня кажется реализованно добавление.
Но не реализованно добывание элементов.

пока завершил, обработку создания поддиректории и файла, куда заливать данные.

на сегодня это скорее всего, вся работа.

== 02.08.2022
Хочется сегодня продолжить, но скаорее всего не получиться.

Один из вариантов, необходимо будет даунгрейднуться до 11 версии явы, ибо под ней собриается кваркус в нативном профиле.

Либо продолжить с докерами, но там.. под 17 версию....
*Диллема*

В итоге, ни чего не делал.

== 03.08.2022
а тут наверное тоже ни чего не будет

== 01.10.2022

Так значит у меня есть 2 метода для создания и 2 метода для забора "Знания"

.забрать знания
. по айди
. по имени

.создать знание
. "корневое" Знание
. и знание под Родителем

ага. т.е. на лицо факт, что считай бекенд у меня есть. а вот фронта нету... как бы мне фронт порисовать?!
или продолжить делать бекенд!?!?!?!?

== 22.10.2022

Однако, у меня работают только эти на добавление.
Однако нет обработки ошибок, что тоже не добавляет понятности как это обрабатывать назад.

Но исправил когда файл уже существует на нужной поддирректории.
А так же форматирование файла добавил.