= Итоги

По факту, журналирование разработки.

== 16.04.2022
Так, сегодня хочу, добавить поиск по ключу.
Идея такая, что я не хочу задумываться над _уникальностью_ генерации ключей.
По этому заменю на UUID. Хотя по факту, даже же оно может и с UUID повторятся.
Но не суть, перепроверку можно организовывать и на UUID.

Короче, основное, у меня нет знания откуда начинать последовательность.
И тут есть как минимум 2 подхода:

1. Записывать текущий счётчик в сам XML, и при создании нового "знания",
нужно будет в него заходить и читать.
2. Использовать генератор уникальных ключей.

Короче да, по поиску пока самое простое использовать Integer.
А потом переделаю на UUID.

== 01.05.2022
Добавил интернализацию.
Всегда надо эту фигню брать.
Ибо все тексты в одном месте.
И править файл ресурса как бы всегда проще, ибо в одном месте.

Так, что еще.
Сделал, обновление существующего Проверки.
А надо доделать еще и этот новая Проверка в Знании, с проверкой, есть ли уже с таким айди, и если есть, то обновить.

== 02.05.2022
Сегодня захотел продолжить эксперименты с моделью.
НО!
Остановился на том, что я свои элементы отдельно друг от друга лепил.
А ведь они же у меня друг в друга вложены!
Как это отобразить-то?!

Или по другому.

Ай была мысля и ушла.
Короче это же эксперимент!!!
А следовательно у меня тонны права на ошибку!

Так хочу порисовать или погоди.
На странице, что видно, Знание -- Проверка -- список Вопросов

Да. Что-то вот делаю-делаю, "атомарно".
И как-то, хочется более, универсального.
Вот этими Дженериками если честно.

Возможно Дженериками во второй итерации.

== 07.05.2022
Так продолжаем, за сегодня надо добить вопросы и ответы.

== 30.07.2022
Однако, как я погружался в работу...

Короче, задача, на деплой на сервер.
Но для этого я хочу чтоб автоматом был файл, если его нет, то создать.
А если есть то использовать его.

И как мне _помнится_ у меня кажется реализованно добавление.
Но не реализованно добывание элементов.

пока завершил, обработку создания поддиректории и файла, куда заливать данные.

на сегодня это скорее всего, вся работа.

== 02.08.2022
Хочется сегодня продолжить, но скаорее всего не получиться.

Один из вариантов, необходимо будет даунгрейднуться до 11 версии явы, ибо под ней собриается кваркус в нативном профиле.

Либо продолжить с докерами, но там.. под 17 версию....
*Диллема*

В итоге, ни чего не делал.

== 03.08.2022
а тут наверное тоже ни чего не будет

== 01.10.2022

Так значит у меня есть 2 метода для создания и 2 метода для забора "Знания"

.забрать знания
. по айди
. по имени

.создать знание
. "корневое" Знание
. и знание под Родителем

ага. т.е. на лицо факт, что считай бекенд у меня есть. а вот фронта нету... как бы мне фронт порисовать?!
или продолжить делать бекенд!?!?!?!?

== 22.10.2022

Однако, у меня работают только эти на добавление.
Однако нет обработки ошибок, что тоже не добавляет понятности как это обрабатывать назад.

Но исправил когда файл уже существует на нужной поддирректории.
А так же форматирование файла добавил.

== 24.11.2022

Что-то упоролся я в получение человеческого XML.
Но проблема в том, что в яве 8 версии это работало, как-то "ожидаемо" и "понятно.
А начиная с версии явы 9 или 11, там они изменили, и добавили, какой-то логики.
И вроде бы должно было стать удобнее, а по факту стало, как-то "непонятно" и "неожиданно".
Отсюда, пошла куча всякой ифнормации, как от этого избавиться.

И где-то в этой куче информации я и сижу.

Ну здрасте мордасте, одно из решений, это использовать валидацию по схеме.
Да и там такие можно включить вот, мол, валиридруй().
Ага, только вот оно не работает! 
Говорит, а где ваш ДТД?!

А это отрывок из официальной документации 

----
To use modern schema languages such as W3C XML Schema or RELAX NG instead of DTD, you can configure your parser to be a non-validating parser by leaving the setValidating(boolean) method false, then use the setSchema(Schema) method to associate a schema to a parser.
----

Т.е. я сейчас буду вот, устанавливать эту схему..

Ну и что!? ну и что за 🤬!?

. я создал схему
. прикрутил ее к файлу
. добавил в коде контроль Схемы, и setIgnoringComments. и что!?

*Итого*: да и всё без толку, когда файл отформатирован, то ДОМ парсер, воспринимает эти пустые стоки как ТЕКСТОВЫЕ-НОДЫ!
И всё. И колбасит их и колбасит....

Короче как я понял, надо без форматирования делать. и тогда это сработает.

Ща проверю.

Ага, без пробелов и без новых строк, всё рабоатет как часы! 
Ни единого сбоя. Да, эта штука какая-то.. хм.. не понятная.

Как обычно хотели как лучше, а получилось как всегда.

Блин опять упоролся со своим проектом в ту штуку, что.
Ну блин XML с ним всё сложно.
Как бы и просто и сложно одновременно.

И даже в начале 2000х, даже были движки БД которые работали на XML файлах как я понял.
(интерсный доклак как я понял http://atterer.org/sites/atterer/files/2010-05/diploma-thesis/efficient-xml-storage.pdf[Efficient Storage of XML Data Streams])

И что!? где я и где моя идея и где мой проект!?!??!?!?

Опять не пойми где всё это шляется.

== 03.12.2022

Нашел сегодня интересную статью про https://habr.com/ru/post/52680/[Оси XPath ]

== 02.01.2023

В целом, короче, с докер образом можно было бы и улучшить, а сейчас оно, чисто опять же для меня.
Но там, как, концептуально оно работает, но для общего случая, всё равно неудобно.

Однако, решение. всё-таки есть, и оно рабочее.

== 10.01.2023 - капец NEO4J HTTP API

Это просто капец!
Я то думал, что HTTP API для Neo4j, это простяцке, и думал я щас как по бырому захвачу в этом. как его, в Свелте.

А оно, ну во-первых, с подключением я провалындался долго. Ну так вот, вроде бы и подключился.

Во-вторых, синтаксис, с  таким синтаксисом, я быстро не уеду ни куда.
То есть возможно, для прокачанного Фронтендера, эта штука вообще ни разу ни где не встала.
Но!
Для меня, изучать чужой синтаксис, чужого фреймворка, это как-то.
И лениво, и ресурса нету.
В голове и так сложно всякое укладывается.

Короче я понял, что опять же по бырому напрямую к НЕО4Джи я не смогу подключиться.
А еще понял, что физически воссоздавать в XML тот формат файлов, вообще какой-то.
Бесперспективный путь. Необходимо обратить внимание, на формать хранения ГеоХЧМЛ или как оно там называется.

== 22.01.2023

Так мне надо записать какие ошибки я не доправил

=== не работает ПОСТ метод для 1 знания - говорит уже такой есть

всё, нашел, там по логике и было, что если нашли то ни чего не делаем.

Но у меня то метод всё таки подразумевал, что всё таки мы значение-то меняем.

так что заправил, на то что оно меняет!

=== не работает ПОСТ метод для внесения в Родительское Знание  - метод не позволен говорит

Заправил, там id не был обнесен в кавычки, так как в xml это же строка, а без кавычек, оно как число говорило.
По этому не могло сконвертировать.