version: "3"

services:
  backend:
    image: psp/mc-01:0.4.0
    container_name:  psp-backend
    hostname: psp-backend
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
      args:
        USER_ID: 
        GROUP_ID: 
    volumes:
      - ./file-storage:/deployments/payload
    ports:
      - 8181:8080 # API
      #- 8443:8443 
    # environment:
    #   - QUARKUS_LAUNCH_DEVMODE=true
    restart: 'no'
