version: "2"

services:
  backend:
    image: psp/mc-01:0.3.2
    container_name:  psp-backend
    hostname: psp-backend
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm.my
      args:
        USER_ID: miroque
        GROUP_ID: miroque
    volumes:
      - ./foo:/deployments/payload
    ports:
      - 8080:8080
      - 8443:8443
    restart: 'no'
