= Эксперименты с моделью и работой через XML
:toc-title: Содержание
:toc: auto

Собственно, эксперимент по модели и проверка, удобно ли работать с файлом XML.
Пока 1/5 где-то, по эксперименту провел.

Очень интересно чем же закончится.

== Основной вектор направления тренировки по сервису

Направления задаю на "Знание".
Т.е. полный путь чисто со знанием, без вложенных элементов!

== Как воспользоваться (Посмотреть)

=== Запуск приложения

Можно приложение стартовать из командной строки.

NOTE: Удостоверьтесь что в системе стоит Java версии не ниже 11. +
В консоле набрать `java -version`

Если есть Apache Maven в системе:

.командой:
----
mvn quarkus:dev
----

Если есть Java, но нет Apache Maven:

.для Windows
----
mvnw.cmd quarkus:dev
----

.для Linux
----
./mvnw quarkus:dev
----

=== Подергать API

Так, как "фронтовой" части пока еще нет.
Можно восользоваться OpenApi веб-интерфейсом http://localhost:8080/q/swagger-ui/

== Как воспользоваться через Docker-compose

=== Создать дирректорию для хранения файла

Там где будет стартовать образ файла.
Необходимо самостоятельно создать дирректорию `file-storage`

.Под линуксом командой:
----
mkdir -v file-storage
----

Я добавляю флаг `-v`, чтоб смотреть результат выполнения програмы.

=== Собрать образ

У меня настроенно докер и докер-композ без `sudo`.

.По этому я запускаю следующей командой:
----
docker-compose build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) backend
----

=== Запустить образ

----
docker-compose up -d backend
----